[package]
name = "ping-pong"
version = "0.0.2"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.dharitri-sc]
version = "0.54.6"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.6"
